### PR TITLE
Sphinx documentation

### LINKED ISSUE #30: how to do random Jitter with CoinFlip
I find that the CropMirrorNormalize op has a 'Mirror' parameter for randomly applying mirror operation,  when it is used with the int tensor generated by the CoinFlip op.
But when I do the samething with the Jitter op it fails(use 'mask' parameter ):  
`RuntimeError: [/opt/dali/dali/pipeline/operators/op_spec.cc:56] Assert on "schema.HasArgument(arg_name)" failed: Argument mask is not part of the op schema`

So how to use the 'mask' parameter in ops like Jitter, Rotate?Or how to apply an augmentation randomly?

### PR DESCRIPTION
**Pull request by ptrendx**
This PR:
- changes the way data types are handled in the OpSchema of the operator and moves some of the logic for type conversion and especially type name conversion to Python
- this enables better Python docstring generation, moved from Markdown to ReStructuredText
- Fix for HasArgument and HasOptionalArgument functions - they now look for arguments in current schema as well as its parents, should fix #30 
- Added Sphinx docs generation based on the Python docstrings

### CODE REVIEW

File: dali/pipeline/operators/op_schema.cc [hunk 1]
```diff
@@ -101,4 +100,65 @@ std::map<std::string, std::pair<std::string, Value*>> OpSchema::GetOptionalArgum
...
+  }
+  return ret;
+}
+
+bool OpSchema::HasRequiredArgument(const std::string &name) const {
+  bool ret = arguments_.find(name) != arguments_.end();
+  if (ret) {
+    return ret;
+  }
+  for (const auto &p : parents_) {
```
Comment (JanuszL) [inline dali/pipeline/operators/op_schema.cc]: I think we should handle transitive parent ship as well (and still defend against cyclic dependency).

Comment (JanuszL) [inline dali/pipeline/operators/op_schema.cc]: Maybe guard against cyclic dependency?

**Comment by JanuszL** [comment]
Maybe it should be split into couple of smaller PR?

File: docs/make.bat [hunk 2]
```diff
@@ -0,0 +1,36 @@
+@ECHO OFF
```
Comment (JanuszL) [inline docs/make.bat]: Do we need that bat?

File: dali/pipeline/operators/op_schema.h [hunk 3]
```diff
@@ -160,11 +166,14 @@ class DLL_PUBLIC OpSchema {
   DLL_PUBLIC inline typename std::enable_if<
     !is_vector<T>::value && !is_array<T>::value,
     OpSchema&>::type
-  AddOptionalArg(const std::string &s, const std::string &doc, T default_value) {
+  AddOptionalArg(const std::string &s, const std::string &doc,
```
[the remark this answers is not in the document]
Comment (ptrendx) [reply dali/pipeline/operators/op_schema.h]: Not sure what you mean?

File: docs/make.bat (hunk 2 above)
Comment (ptrendx) [reply docs/make.bat]: Sphinx makes it automatically in case we wanted to build docs on Windows, but since we don't I can remove it.

File: dali/pipeline/operators/op_schema.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (JanuszL) [reply dali/pipeline/operators/op_schema.h]: DLL_PUBLIC inline OpSchema& AddArg(const std::string &s,
                                     const std::string &doc,
                                     const DALIDataType dtype,
                                     bool enable_tensor_input = false) {
vs

    DLL_PUBLIC inline typename std::enable_if<
         !is_vector<T>::value && !is_array<T>::value,
         OpSchema&>::type
     AddOptionalArg(const std::string &s, const std::string &doc,
                                     T default_value, bool enable_tensor_input = false) {

It is detail anyway, but how about:

    DLL_PUBLIC inline typename std::enable_if<
         !is_vector<T>::value && !is_array<T>::value,
         OpSchema&>::type AddOptionalArg(const std::string &s,
                                     const std::string &doc,
                                     T default_value,
                                     bool enable_tensor_input = false) {

[the remark this answers is not in the document]
Comment (ptrendx) [reply dali/pipeline/operators/op_schema.h]: Ok

File: dali/pipeline/data/types.h [hunk 4]
```diff
@@ -270,6 +182,98 @@ class DLL_PUBLIC TypeInfo {
...
+    return id_it->second;
+  }
+
+ private:
+  // TypeTable should only be referenced through its static members
+  TypeTable();
+
+  template <typename T>
+  static DALIDataType RegisterType(DALIDataType dtype) {
+    // Lock the mutex to ensure correct setup even if this
```
[the remark this answers is not in the document]
Comment (ptrendx) [reply dali/pipeline/data/types.h]: Ok, I will change the comment.

File: dali/pipeline/operators/op_schema.cc (hunk 1 above)
Comment (ptrendx) [reply dali/pipeline/operators/op_schema.cc]: That will be hard without actually creating either the list of schemas already seen or list of arguments already seen (so that you could check for duplicates). 

Adding test that would catch that (and making docs would) is enough I think.

Comment (JanuszL) [reply dali/pipeline/operators/op_schema.cc]: OK. Sounds reasonable. How about adding some note that addParent doesn't support cyclic dependency.

Comment (ptrendx) [reply dali/pipeline/operators/op_schema.cc]: Sure, I will add that.
